# Snorby Database Configuration
#
# Please set your database password/user below
#
snorby: &snorby
  adapter: mysql2
  username: root
  password: s3cr3tsauce
  host: localhost

development:
  database: snorby
  <<: *snorby

test:
  database: snorby
  <<: *snorby

production:
  database: snorby
  <<: *snorby
